-- Portable Blockwise schema. Run in Supabase SQL editor or PostgreSQL on a VPS.
create extension if not exists "uuid-ossp";
create table if not exists buildings (id uuid primary key default uuid_generate_v4(), name text not null, area text, address text, floors int, zoning text, notes text, created_at timestamptz default now());
create table if not exists apartments (id uuid primary key default uuid_generate_v4(), building_id uuid references buildings(id) on delete cascade, unit_number text not null, floor int, bedrooms numeric, square_meters numeric, status text not null default 'vacant', owner_name text, tenant_name text, phone text, asking_rent numeric, lease_start date, lease_end date, vacant_since date, market_posted_at date, yad2_url text, notes text, created_at timestamptz default now());
create table if not exists rent_charges (id uuid primary key default uuid_generate_v4(), apartment_id uuid references apartments(id) on delete cascade, period_start date not null, period_end date not null, amount numeric not null, due_date date, status text default 'pending', payment_method text, paid_at date, notes text);
create table if not exists bills (id uuid primary key default uuid_generate_v4(), apartment_id uuid references apartments(id) on delete cascade, category text not null, provider text, account_number text, policy_number text, billed_to text, period_start date, period_end date, amount numeric, status text default 'unpaid', payment_method text, paid_at date, attachment_path text, notes text);
create table if not exists maintenance (id uuid primary key default uuid_generate_v4(), apartment_id uuid references apartments(id) on delete cascade, building_id uuid references buildings(id) on delete cascade, title text not null, description text, status text default 'open', priority text default 'normal', vendor text, cost numeric default 0, opened_at date default current_date, completed_at date, notes text);
create table if not exists documents (id uuid primary key default uuid_generate_v4(), apartment_id uuid references apartments(id) on delete cascade, building_id uuid references buildings(id) on delete cascade, file_path text not null, category text, uploaded_at timestamptz default now());
alter table buildings enable row level security; alter table apartments enable row level security; alter table rent_charges enable row level security; alter table bills enable row level security; alter table maintenance enable row level security; alter table documents enable row level security;
-- Add authenticated-user policies after creating your workspace_members table. Never expose service keys in the browser.
