// Seed/demo data is isolated here. It is only loaded when the user chooses Load mock data.
const seed = {
  buildings: [
    {
      id: 'b1',
      name: 'Gimel 4',
      street: 'חנה סנש',
      address: 'חנה סנש 4, שכונה ג׳, באר שבע',
      lat: 31.2641,
      lng: 34.7986,
      area: 'Shechuna Gimel',
      units: 18,
      floors: 6,
      zone: 'Residential A',
      color: 'coral',
      x: 27,
      y: 26,
    },
    {
      id: 'b2',
      name: 'Gimel 15',
      street: 'השלום',
      address: 'השלום 15, שכונה ג׳, באר שבע',
      lat: 31.26455,
      lng: 34.7994,
      area: 'Shechuna Gimel',
      units: 24,
      floors: 8,
      zone: 'Mixed use',
      color: 'blue',
      x: 55,
      y: 37,
    },
    {
      id: 'b3',
      name: 'HaKaf Gimel 4',
      street: 'גוש עציון',
      address: 'גוש עציון 4, שכונה ג׳, באר שבע',
      lat: 31.26345,
      lng: 34.8002,
      area: 'Shechuna Gimel',
      units: 12,
      floors: 4,
      zone: 'Residential B',
      color: 'mint',
      x: 71,
      y: 19,
    },
    {
      id: 'b4',
      name: 'Gimel 22',
      street: 'רוטנברג',
      address: 'רוטנברג 22, שכונה ג׳, באר שבע',
      lat: 31.2629,
      lng: 34.7991,
      area: 'Shechuna Gimel',
      units: 30,
      floors: 10,
      zone: 'Residential A',
      color: 'gold',
      x: 38,
      y: 67,
    },
  ],
  apartments: [
    {
      id: 'a1',
      buildingId: 'b1',
      number: 'A-01',
      resident: 'Maya Cohen',
      ownerName: 'Avi Cohen',
      tenantName: 'Maya Cohen',
      leaseStart: '2024-07-01',
      leaseEnd: '2026-06-30',
      contractUrl: '',
      status: 'Leased',
      rent: 4850,
      due: '2024-07-01',
    },
    {
      id: 'a2',
      buildingId: 'b1',
      number: 'A-02',
      resident: 'Noam Levi',
      ownerName: 'Ruth Levi',
      tenantName: 'Noam Levi',
      leaseStart: '2023-10-15',
      leaseEnd: '2025-10-14',
      contractUrl: '',
      status: 'Leased',
      rent: 5200,
      due: '2023-10-15',
    },
    {
      id: 'a3',
      buildingId: 'b1',
      number: 'A-03',
      resident: '',
      ownerName: 'Miriam Azulay',
      tenantName: '',
      leaseStart: '',
      leaseEnd: '',
      contractUrl: '',
      status: 'Vacant',
      rent: 4600,
      due: '2025-06-03',
    },
    {
      id: 'a4',
      buildingId: 'b1',
      number: 'A-04',
      resident: 'Dana Shalev',
      ownerName: 'Oren Shalev',
      tenantName: 'Dana Shalev',
      leaseStart: '2025-07-01',
      leaseEnd: '2026-06-30',
      contractUrl: '',
      status: 'On market',
      rent: 5100,
      due: '2025-06-27',
    },
  ],
  maintenance: [
    {
      id: 'm1',
      buildingId: 'b1',
      title: 'Leaking kitchen tap',
      status: 'Open',
      cost: 420,
      date: '2025-06-28',
    },
  ],
  bills: [],
  payments: [],
  activity: [],
  people: [
    { id: 'p1', name: 'Avi Cohen', role: 'Owner', phone: '050-555-1040', apartmentIds: ['a1'] },
    { id: 'p2', name: 'Maya Cohen', role: 'Tenant', phone: '052-555-2091', apartmentIds: ['a1'] },
    { id: 'p3', name: 'Ruth Levi', role: 'Owner', phone: '050-555-3082', apartmentIds: ['a2'] },
    { id: 'p4', name: 'Noam Levi', role: 'Tenant', phone: '054-555-4102', apartmentIds: ['a2'] },
    {
      id: 'p5',
      name: 'Yossi Electric',
      role: 'Technician',
      phone: '050-555-9012',
      apartmentIds: [],
    },
    {
      id: 'p6',
      name: 'Neta Barak',
      role: 'Insurance agent',
      phone: '052-555-8801',
      apartmentIds: [],
    },
  ],
};
const money = (n) => `₪${Number(n || 0).toLocaleString('en-US')}`;
const mockExpansion = {
  buildings: [
    {
      id: 'b5',
      name: 'Gimel 28',
      street: 'נילי',
      address: 'נילי 28, שכונה ג׳, באר שבע',
      lat: 31.26375,
      lng: 34.8011,
      area: 'Shechuna Gimel',
      units: 16,
      floors: 5,
      zone: 'Residential A',
      color: 'coral',
      x: 18,
      y: 45,
    },
    {
      id: 'b6',
      name: 'Gimel 33',
      street: 'וינגייט',
      address: 'וינגייט 33, שכונה ג׳, באר שבע',
      lat: 31.2626,
      lng: 34.80055,
      area: 'Shechuna Gimel',
      units: 20,
      floors: 7,
      zone: 'Residential B',
      color: 'blue',
      x: 63,
      y: 60,
    },
    {
      id: 'b7',
      name: 'Gimel 41',
      street: 'בן גוריון',
      address: 'בן גוריון 41, שכונה ג׳, באר שבע',
      lat: 31.26485,
      lng: 34.80125,
      area: 'Shechuna Gimel',
      units: 14,
      floors: 4,
      zone: 'Residential A',
      color: 'mint',
      x: 82,
      y: 42,
    },
    {
      id: 'b8',
      name: 'Gimel 48',
      street: 'רזיאל',
      address: 'רזיאל 48, שכונה ג׳, באר שבע',
      lat: 31.2632,
      lng: 34.80185,
      area: 'Shechuna Gimel',
      units: 12,
      floors: 4,
      zone: 'Residential A',
      color: 'gold',
      x: 76,
      y: 72,
    },
  ],
  apartments: [
    {
      id: 'a5',
      buildingId: 'b1',
      number: 'A-05',
      ownerName: 'Shira Ben-David',
      tenantName: 'Lior Katz',
      resident: 'Lior Katz',
      status: 'Leased',
      rent: 4950,
      leaseStart: '2025-02-01',
      leaseEnd: '2026-01-31',
      contractUrl: '',
    },
    {
      id: 'a6',
      buildingId: 'b2',
      number: 'B-01',
      ownerName: 'Eli Mizrahi',
      tenantName: 'Yael Peretz',
      resident: 'Yael Peretz',
      status: 'Leased',
      rent: 5600,
      leaseStart: '2024-09-01',
      leaseEnd: '2026-08-31',
      contractUrl: '',
    },
    {
      id: 'a7',
      buildingId: 'b2',
      number: 'B-02',
      ownerName: 'Eli Mizrahi',
      tenantName: '',
      resident: '',
      status: 'Vacant',
      rent: 5400,
      leaseStart: '',
      leaseEnd: '',
      contractUrl: '',
    },
    {
      id: 'a8',
      buildingId: 'b3',
      number: '2',
      ownerName: 'Tal Shachar',
      tenantName: 'Roni Gil',
      resident: 'Roni Gil',
      status: 'Leased',
      rent: 6100,
      leaseStart: '2025-04-15',
      leaseEnd: '2026-04-14',
      contractUrl: '',
    },
    {
      id: 'a9',
      buildingId: 'b3',
      number: '3',
      ownerName: 'Tal Shachar',
      tenantName: '',
      resident: '',
      status: 'On market',
      rent: 6250,
      leaseStart: '',
      leaseEnd: '',
      contractUrl: '',
    },
    {
      id: 'a10',
      buildingId: 'b4',
      number: '1',
      ownerName: 'Nir Avital',
      tenantName: 'Ofir Cohen',
      resident: 'Ofir Cohen',
      status: 'Leased',
      rent: 4700,
      leaseStart: '2024-12-01',
      leaseEnd: '2025-11-30',
      contractUrl: '',
    },
    {
      id: 'a11',
      buildingId: 'b4',
      number: '2',
      ownerName: 'Nir Avital',
      tenantName: '',
      resident: '',
      status: 'Vacant',
      rent: 4650,
      leaseStart: '',
      leaseEnd: '',
      contractUrl: '',
    },
    {
      id: 'a12',
      buildingId: 'b5',
      number: '1',
      ownerName: 'Michal Azulay',
      tenantName: 'Amit Ronen',
      resident: 'Amit Ronen',
      status: 'Leased',
      rent: 4550,
      leaseStart: '2025-01-15',
      leaseEnd: '2026-01-14',
      contractUrl: '',
    },
    {
      id: 'a13',
      buildingId: 'b5',
      number: '2',
      ownerName: 'Michal Azulay',
      tenantName: '',
      resident: '',
      status: 'Vacant',
      rent: 4500,
      leaseStart: '',
      leaseEnd: '',
      contractUrl: '',
    },
    {
      id: 'a14',
      buildingId: 'b6',
      number: '1',
      ownerName: 'Gadi Fried',
      tenantName: 'Hila Naveh',
      resident: 'Hila Naveh',
      status: 'Leased',
      rent: 5750,
      leaseStart: '2025-06-01',
      leaseEnd: '2026-05-31',
      contractUrl: '',
    },
    {
      id: 'a15',
      buildingId: 'b6',
      number: '2',
      ownerName: 'Gadi Fried',
      tenantName: 'Matan Bar',
      resident: 'Matan Bar',
      status: 'Leased',
      rent: 5800,
      leaseStart: '2024-11-01',
      leaseEnd: '2025-10-31',
      contractUrl: '',
    },
    {
      id: 'a16',
      buildingId: 'b6',
      number: '3',
      ownerName: 'Gadi Fried',
      tenantName: '',
      resident: '',
      status: 'On market',
      rent: 5900,
      leaseStart: '',
      leaseEnd: '',
      contractUrl: '',
    },
    {
      id: 'a17',
      buildingId: 'b7',
      number: '1',
      ownerName: 'Anat Levi',
      tenantName: 'Shani Dahan',
      resident: 'Shani Dahan',
      status: 'Leased',
      rent: 5100,
      leaseStart: '2025-03-01',
      leaseEnd: '2026-02-28',
      contractUrl: '',
    },
    {
      id: 'a18',
      buildingId: 'b7',
      number: '2',
      ownerName: 'Anat Levi',
      tenantName: '',
      resident: '',
      status: 'Vacant',
      rent: 5000,
      leaseStart: '',
      leaseEnd: '',
      contractUrl: '',
    },
    {
      id: 'a19',
      buildingId: 'b7',
      number: '3',
      ownerName: 'Anat Levi',
      tenantName: 'Yarden Shalev',
      resident: 'Yarden Shalev',
      status: 'Leased',
      rent: 5150,
      leaseStart: '2024-08-01',
      leaseEnd: '2025-07-31',
      contractUrl: '',
    },
  ],
  people: [
    {
      id: 'p7',
      name: 'Shira Ben-David',
      role: 'Owner',
      phone: '050-555-6111',
      apartmentIds: ['a5'],
    },
    { id: 'p8', name: 'Lior Katz', role: 'Tenant', phone: '052-555-6222', apartmentIds: ['a5'] },
    {
      id: 'p9',
      name: 'Eli Mizrahi',
      role: 'Owner',
      phone: '050-555-6333',
      apartmentIds: ['a6', 'a7'],
    },
    { id: 'p10', name: 'Yael Peretz', role: 'Tenant', phone: '054-555-6444', apartmentIds: ['a6'] },
    {
      id: 'p11',
      name: 'Tal Shachar',
      role: 'Owner',
      phone: '052-555-6555',
      apartmentIds: ['a8', 'a9'],
    },
    { id: 'p12', name: 'Roni Gil', role: 'Tenant', phone: '050-555-6666', apartmentIds: ['a8'] },
    {
      id: 'p13',
      name: 'Nir Avital',
      role: 'Owner',
      phone: '054-555-6777',
      apartmentIds: ['a10', 'a11'],
    },
    { id: 'p14', name: 'Ofir Cohen', role: 'Tenant', phone: '052-555-6888', apartmentIds: ['a10'] },
    {
      id: 'p15',
      name: 'Michal Azulay',
      role: 'Owner',
      phone: '050-555-6999',
      apartmentIds: ['a12', 'a13'],
    },
    { id: 'p16', name: 'Amit Ronen', role: 'Tenant', phone: '054-555-7000', apartmentIds: ['a12'] },
    {
      id: 'p17',
      name: 'Gadi Fried',
      role: 'Owner',
      phone: '052-555-7111',
      apartmentIds: ['a14', 'a15', 'a16'],
    },
    { id: 'p18', name: 'Hila Naveh', role: 'Tenant', phone: '050-555-7222', apartmentIds: ['a14'] },
    { id: 'p19', name: 'Matan Bar', role: 'Tenant', phone: '054-555-7333', apartmentIds: ['a15'] },
    {
      id: 'p20',
      name: 'Anat Levi',
      role: 'Owner',
      phone: '052-555-7444',
      apartmentIds: ['a17', 'a18', 'a19'],
    },
    {
      id: 'p21',
      name: 'Shani Dahan',
      role: 'Tenant',
      phone: '050-555-7555',
      apartmentIds: ['a17'],
    },
    {
      id: 'p22',
      name: 'Yarden Shalev',
      role: 'Tenant',
      phone: '054-555-7666',
      apartmentIds: ['a19'],
    },
  ],
};
const spreadsheetImport = {
  buildings: [
    {
      id: 'b9',
      name: 'חנה סנש 8',
      street: 'חנה סנש',
      streetNumber: '8',
      address: 'חנה סנש 8, שכונה ג׳, באר שבע',
      area: 'Shechuna Gimel',
      units: 1,
      floors: 2,
      zone: 'Residential',
      color: 'gold',
      lat: 31.2643,
      lng: 34.7989,
    },
  ],
  apartments: [
    {
      id: 'a20',
      buildingId: 'b9',
      uniqueId: '3228',
      apptId: 'U001',
      number: '5',
      entrance: 'ד',
      street: 'חנה סנש',
      streetNumber: '8',
      altAddress: 'חנה סנש 28\\8',
      addressNotEditable: 'חנה סנש 8/5',
      rooms: 2,
      garden: false,
      floor: 2,
      size: 38.2,
      parcel: 32,
      subA: 28,
      ownerName: 'HD',
      owner1: '',
      owner2: '',
      id1: '',
      id2: '',
      phone1: '',
      phone2: '',
      warning: '',
      propertyClass: 'Owned',
      internalOwner: '',
      note: '',
      validated: true,
      validationDate: '2023-06-15T15:31:08',
      ownerContract: 'השקעות דרום',
      invested: 535282,
      housewares: '',
      agreement: '',
      rentable: true,
      representative: 'jhs73vgs',
      lawyer: '',
      pinuiStatus: '1. yet started Process',
      tenantName: '',
      resident: '',
      status: 'Vacant',
      rent: 0,
      leaseStart: '',
      leaseEnd: '',
      contractUrl: '',
    },
  ],
  people: [
    {
      id: 'p23',
      name: 'HD',
      role: 'Owner',
      phone: '',
      apartmentIds: ['a20'],
      notes: 'Imported owner record',
    },
  ],
};
const bulkApartments = Array.from({ length: 8 }, (_, index) => ({
  id: `bulk-${index}`,
  buildingId: `b${index + 1}`,
  number: `G-${index + 1}`,
  ownerName: ['Amidar', 'Amidar', 'Amidar', 'HD', 'HD', 'MR', 'Individual owner', 'Amidar'][index],
  tenantName: index % 3 === 1 ? '' : `Sample tenant ${index + 1}`,
  resident: index % 3 === 1 ? '' : `Sample tenant ${index + 1}`,
  status: index % 3 === 1 ? 'Vacant' : index === 5 ? 'On market' : 'Leased',
  rent: 4300 + index * 175,
  leaseStart: index % 3 === 1 ? '' : `2025-0${(index % 8) + 1}-01`,
  leaseEnd: index % 3 === 1 ? '' : `2026-0${(index % 8) + 1}-01`,
  contractUrl: '',
}));
const bulkEvents = bulkApartments.flatMap((apartment, index) => [
  {
    id: `event-${index}-1`,
    apartmentId: apartment.id,
    type: 'Maintenance',
    title: index % 2 ? 'Furniture replacement' : 'Kitchen leak repair',
    date: '2025-06-12',
    cost: 180 + index * 35,
    notes: 'Mock maintenance record',
  },
  {
    id: `event-${index}-2`,
    apartmentId: apartment.id,
    type: 'Inspection',
    title: 'Annual apartment inspection',
    date: '2025-05-04',
    cost: 0,
    notes: 'Routine visit completed',
  },
]);
const bulkBills = bulkApartments.flatMap((apartment, index) =>
  ['Water', 'Electricity', 'Vaad', 'Arnona', 'Gas'].map((category, billIndex) => ({
    id: `bill-${index}-${billIndex}`,
    apartmentId: apartment.id,
    category,
    amount: 90 + index * 17 + billIndex * 23,
    period: '2025-06-01 to 2025-06-30',
    dueDate: '2025-07-15',
    status: billIndex === 2 && index % 2 === 0 ? 'Unpaid' : 'Paid',
  }))
);
const insuranceProviders = [
  { name: 'Phoenix', agent: 'Dana Shavit', phone: '03-555-1200', email: 'dana.shavit@example.com' },
  { name: 'Migdal', agent: 'Omer Katz', phone: '03-555-2300', email: 'omer.katz@example.com' },
  {
    name: 'Menora',
    agent: 'Ravit Azulay',
    phone: '03-555-3400',
    email: 'ravit.azulay@example.com',
  },
];
const maintenanceTypes = [
  ['Leak repair', 'Maintenance', 'Yossi Electric'],
  ['Annual inspection', 'Inspection', 'Maya Services'],
  ['Paint job', 'Renovation', 'Color Team'],
  ['Appliance replacement', 'Appliance', 'HomeTech Beersheba'],
];
const buildApartmentOperations = (apartments) => ({
  apartments: apartments.map((apartment, index) => {
    const insurance = insuranceProviders[index % insuranceProviders.length];
    return {
      ...apartment,
      insuranceProvider: insurance.name,
      policyNumber: `POL-${100000 + index}`,
      policyStart: '2025-01-01',
      policyEnd: '2025-12-31',
      insuranceAgent: insurance.agent,
      insuranceAgentPhone: insurance.phone,
      insuranceAgentEmail: insurance.email,
    };
  }),
  maintenance: apartments.flatMap((apartment, index) =>
    maintenanceTypes.map((item, typeIndex) => ({
      id: `maint-${apartment.id}-${typeIndex}`,
      apartmentId: apartment.id,
      buildingId: apartment.buildingId,
      title: item[0],
      category: item[1],
      technician: item[2],
      insuranceAgent: index % 3 === 0 ? insuranceProviders[index % 3].agent : '',
      date: `2025-0${(typeIndex % 6) + 1}-${String((index % 20) + 1).padStart(2, '0')}`,
      cost: 180 + index * 22 + typeIndex * 95,
      status: typeIndex === 1 ? 'Done' : index % 4 === 0 ? 'In progress' : 'Done',
      notes: 'Mock operational record — edit me',
    }))
  ),
});
const enrichPerson = (person, index = 0) => ({
  ...person,
  email: person.email || `${person.name.toLowerCase().replaceAll(' ', '.')}@example.com`,
  preferredContact: person.preferredContact || (index % 2 ? 'WhatsApp' : 'Phone'),
  notes:
    person.notes ||
    (person.role === 'Owner'
      ? 'One with the garden'
      : person.role === 'Tenant'
        ? 'Daughter of a former resident'
        : 'Reliable contact for urgent callouts'),
  interactions:
    person.interactions ||
    (['Technician', 'Insurance agent'].includes(person.role)
      ? [
          {
            id: `${person.id}-i1`,
            apartment: person.apartmentIds?.[0] || 'Portfolio callout',
            date: '2025-06-12',
            title: person.role === 'Technician' ? 'Leak repair' : 'Policy review',
            cost: person.role === 'Technician' ? 420 : 0,
          },
          {
            id: `${person.id}-i2`,
            apartment: person.apartmentIds?.[1] || 'Building visit',
            date: '2025-05-04',
            title: 'Follow-up visit',
            cost: person.role === 'Technician' ? 180 : 0,
          },
        ]
      : []),
});

export { seed, mockExpansion, spreadsheetImport, bulkApartments, bulkEvents, bulkBills, buildApartmentOperations };
